INSERT INTO provincias(Id,Nombre) VALUES (02,'Albacete');
INSERT INTO provincias(Id,Nombre) VALUES (03,'Alicante/Alacant');
INSERT INTO provincias(Id,Nombre) VALUES (04,'Almería');
INSERT INTO provincias(Id,Nombre) VALUES (01,'Araba/Álava');
INSERT INTO provincias(Id,Nombre) VALUES (33,'Asturias');
INSERT INTO provincias(Id,Nombre) VALUES (05,'Ávila');
INSERT INTO provincias(Id,Nombre) VALUES (06,'Badajoz');
INSERT INTO provincias(Id,Nombre) VALUES (07,'Balears, Illes');
INSERT INTO provincias(Id,Nombre) VALUES (08,'Barcelona');
INSERT INTO provincias(Id,Nombre) VALUES (48,'Bizkaia');
INSERT INTO provincias(Id,Nombre) VALUES (09,'Burgos');
INSERT INTO provincias(Id,Nombre) VALUES (10,'Cáceres');
INSERT INTO provincias(Id,Nombre) VALUES (11,'Cádiz');
INSERT INTO provincias(Id,Nombre) VALUES (39,'Cantabria');
INSERT INTO provincias(Id,Nombre) VALUES (12,'Castellón/Castelló');
INSERT INTO provincias(Id,Nombre) VALUES (13,'Ciudad Real');
INSERT INTO provincias(Id,Nombre) VALUES (14,'Córdoba');
INSERT INTO provincias(Id,Nombre) VALUES (15,'Coruña, A');
INSERT INTO provincias(Id,Nombre) VALUES (16,'Cuenca');
INSERT INTO provincias(Id,Nombre) VALUES (20,'Gipuzkoa');
INSERT INTO provincias(Id,Nombre) VALUES (17,'Girona');
INSERT INTO provincias(Id,Nombre) VALUES (18,'Granada');
INSERT INTO provincias(Id,Nombre) VALUES (19,'Guadalajara');
INSERT INTO provincias(Id,Nombre) VALUES (21,'Huelva');
INSERT INTO provincias(Id,Nombre) VALUES (22,'Huesca');
INSERT INTO provincias(Id,Nombre) VALUES (23,'Jaén');
INSERT INTO provincias(Id,Nombre) VALUES (24,'León');
INSERT INTO provincias(Id,Nombre) VALUES (25,'Lleida');
INSERT INTO provincias(Id,Nombre) VALUES (27,'Lugo');
INSERT INTO provincias(Id,Nombre) VALUES (28,'Madrid');
INSERT INTO provincias(Id,Nombre) VALUES (29,'Málaga');
INSERT INTO provincias(Id,Nombre) VALUES (30,'Murcia');
INSERT INTO provincias(Id,Nombre) VALUES (31,'Navarra');
INSERT INTO provincias(Id,Nombre) VALUES (32,'Ourense');
INSERT INTO provincias(Id,Nombre) VALUES (34,'Palencia');
INSERT INTO provincias(Id,Nombre) VALUES (35,'Palmas, Las');
INSERT INTO provincias(Id,Nombre) VALUES (36,'Pontevedra');
INSERT INTO provincias(Id,Nombre) VALUES (26,'Rioja, La');
INSERT INTO provincias(Id,Nombre) VALUES (37,'Salamanca');
INSERT INTO provincias(Id,Nombre) VALUES (38,'Santa Cruz de Tenerife');
INSERT INTO provincias(Id,Nombre) VALUES (40,'Segovia');
INSERT INTO provincias(Id,Nombre) VALUES (41,'Sevilla');
INSERT INTO provincias(Id,Nombre) VALUES (42,'Soria');
INSERT INTO provincias(Id,Nombre) VALUES (43,'Tarragona');
INSERT INTO provincias(Id,Nombre) VALUES (44,'Teruel');
INSERT INTO provincias(Id,Nombre) VALUES (45,'Toledo');
INSERT INTO provincias(Id,Nombre) VALUES (46,'Valencia/València');
INSERT INTO provincias(Id,Nombre) VALUES (47,'Valladolid');
INSERT INTO provincias(Id,Nombre) VALUES (49,'Zamora');
INSERT INTO provincias(Id,Nombre) VALUES (50,'Zaragoza');
INSERT INTO provincias(Id,Nombre) VALUES (51,'Ceuta');
INSERT INTO provincias(Id,Nombre) VALUES (52,'Melilla');